/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package listaligada;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.BoxLayout;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 * Esta es la clase Crea la cual sirve para crear la tabla y agrearle campos
 * @author Anita, Andy, Zuleyka 
 */
public class Crea extends javax.swing.JFrame {
    /**
     * Esta es la variable alTextos de tipo ArrayList en la cual se guarda el nombre del campo 
     * que haya creado el usuario
     */
    private ArrayList <JTextField> alTextos;
    /**
     * Esta es la variable alTipos de tipo ArrayList en la cual se guarda el tipo de dato
     * del campo que haya creado el usuario
     */
    private ArrayList <JComboBox> alTipos;
    /**
     * Creates new form Crea
     */
    public Crea() {
        lf();
        initComponents();
        alTextos = new ArrayList();
        alTipos = new ArrayList();
        jPanel1.setLayout(new BoxLayout(jPanel1, BoxLayout.Y_AXIS));
        agregaCampos();
    }
    /***
     * Este es el metodo agregaCampos() en el cual se declara un arreglo de tipo String 
     * para indicar los tipos de datos permitidos para cada campo.
     */
    public void agregaCampos(){
        String [] tipos = {"Texto", "Numérico", "Fecha"};
        JPanel orden = new JPanel(new GridLayout(1, 4));
        orden.setMaximumSize(new Dimension(500, 30));
        JLabel lblNombre = new JLabel("Nombre del campo");
//        lblNombre.setSize(150, 20);
        JLabel lblTipo = new JLabel("Tipo");
//        lblTipo.setSize(50, 20);
        JTextField txtNombre = new JTextField(12);
//        txtNombre.setSize(150, 20);
        JComboBox cbxTipo = new JComboBox(tipos);
//        cbxTipo.setSize(150, 20);
        
        orden.add(lblNombre);
        orden.add(txtNombre);
        orden.add(lblTipo);
        orden.add(cbxTipo);
        jPanel1.add(orden, BorderLayout.SOUTH);
        jPanel1.updateUI();
        alTextos.add(txtNombre);
        alTipos.add(cbxTipo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar tabla");

        jLabel1.setText("Nombre de la tabla:");

        jTextField1.setColumns(12);

        jButton1.setText("Agregar campo >");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 215, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * En este metodo se manda a llamar al metodo agregaCampos() de la clase
     * @param evt 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        agregaCampos();
    }//GEN-LAST:event_jButton1ActionPerformed
/***
     * En este metodo primero se recoore la lista based de la clase Bd para verificar que el nombre de la  tabla a crear 
     * no se repita y si el nombre de la tabla se repite se enciende la bandera repetida y se arroja un mensaje diciendo que 
     * el nombre de la tabla ya existe, en caso contrario se recorre el ArrayList alTextos y se le agrega a la lista encabezado 
     * un objeto de tipo Campo que se crea pasandole al constructor el nombre y el tipo de dato del campo.
     * @param evt 
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Tabla t;
        ListaLigada encabezado = new ListaLigada();
        boolean repetida = false;
        
        for(int i = 0; i < Bd.based.size(); i++)
            if(((Tabla) Bd.based.get(i).getDato()).getNombre().equalsIgnoreCase(jTextField1.getText())){
                repetida = true;
                break;
            }
        
        if(!repetida){
            t = new Tabla(jTextField1.getText());

            for(int i = 0; i < alTextos.size(); i++)
                encabezado.agregar(new Campo(alTextos.get(i).getText(), alTipos.get(i).getSelectedIndex()));

            t.getRegistros().agregar(encabezado);
            Bd.based.agregar(t);

            this.dispose();
        }
        else
            JOptionPane.showMessageDialog(this, "El nombre de tabla ya existe.");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void lf() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
